#!/bin/sh

: << =cut

=head1 NAME

lxc_proc - Plugin to monitor LXC Processes count

=head1 CONFIGURATION

env.cgrouppath - Set the path where 'tasks' sysfs files are stored, default: empty

  [lxc_proc]
    user root
    env.cgrouppath /sys/fs/cgroup/cpuacct/lxc/

=head1 INTERPRETATION

This plugin needs root privilege.

=head1 AUTHOR

vajtsz  vajtsz@gmail.com
alpha_one_x86   alpha_one_x86@firt-world.info

=head1 LICENSE

Unknown license

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. /usr/libexec/munin/plugins/plugin.sh

## find proper sysfs and count it
# Debian 6.0: /sys/fs/cgroup/<container>/tasks
# Ubuntu 12.04 with fstab: /sys/fs/cgroup/lxc/<container>/tasks
# Ubuntu 12.04 with cgroup-lite: /sys/fs/cgroup/cpuacct/lxc/<container>/tasks
# Ubuntu 12.04 with cgroup-bin: /sys/fs/cgroup/cpuacct/sysdefault/lxc/<container>/tasks
# Ubuntu 14.04: /sys/fs/cgroup/systemd/lxc/<container>/tasks
count_processes () {
    [ -z "$1" ] && return 0
    return `wc -l < /sys/fs/cgroup/cpuacct/lxc/$1/tasks`
}

#don't use lxc-ls + ls-info + RUNNING: huge performance improvements 8s -> 0.01s
for guest in `find /sys/fs/cgroup/cpuacct/lxc/ -maxdepth 1 -mindepth 1 -type d -printf '%f\n' | sort -u`; do
    guest_names="$guest_names $guest"
done

f_comm='lxc-cgroup  '

if [ "$1" = "autoconf" ]; then
	if [ -r /proc/stat ]; then
		echo yes
		exit 0
	else
		echo "no (no /proc/stat)"
		exit 0
	fi
fi

if [ "$1" = "config" ]; then

 echo 'graph_title Processes thread '
 echo 'graph_args -l 0 --base 1000'
 echo 'graph_vlabel Number of processes'
 echo 'graph_category lxc'

 
 for guest_name in $guest_names;
 do 
  guest="$(clean_fieldname $guest_name)"
  echo 'lxc_proc_'$guest'.label '$guest_name
  echo 'lxc_proc_'$guest'.type GAUGE'
  echo 'lxc_proc_'$guest'.min 0'
 done
 exit 0
fi

 for guest_name in $guest_names;
 do 
  guest="$(clean_fieldname $guest_name)"
  
  count_processes $guest_name
  tmp_g=$?
  if [ $tmp_g -eq 0 ]; then
    tmp_g=`$f_comm -n $guest_name tasks | wc -l`
  fi
  echo 'lxc_proc_'$guest'.value '$tmp_g
  

 done


