#!/bin/bash
# -*- sh -*-

: << =cut

=head1 NAME

lxc_ram - Plugin to monitor LXC memory usage.

=head1 CONFIGURATION

  [lxc_*]
    user root

This is a wildcard plugin. To monitor memory usage for a LXC container,
link lxc_ram_<container> to this file. For example,

  ln -s /usr/share/munin/plugins/lxc_ram_ \
        /etc/munin/plugins/lxc_ram_mycontainer

will monitor the container "mycontainer".

=head1 INTERPRETATION

This plugin needs root privilege.

=head1 AUTHOR

vajtsz vajtsz@gmail.com
mitty   mitty@mitty.jp
Baptiste Jonglez

=head1 LICENSE

Unknown license

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf suggest

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

CONTAINER="${0##*lxc_ram_}"

f_comm='lxc-cgroup  '

case $1 in
    autoconf)
	if [ -r /proc/stat ]; then
		echo yes
		exit 0
	else
		echo "no (no /proc/stat)"
		exit 0
	fi
        ;;
    suggest)
        lxc-ls -1
        exit 0
        ;;
    config)
        echo "graph_title Memory usage for LXC container $CONTAINER "
        echo 'graph_args -l 0 --base 1024'
        echo 'graph_vlabel byte'
        echo 'graph_category virtualization'
        echo 'mem_usage.label Mem usage'
        echo 'mem_usage.type GAUGE'
        echo 'mem_cache.label Cache'
        echo 'mem_cache.type GAUGE'
        echo 'mem_active.label Active'
        echo 'mem_active.type GAUGE'
        echo 'mem_inactive.label Inactive'
        echo 'mem_inactive.type GAUGE'
        exit 0
        ;;
esac

tmp_v=$($f_comm -n $CONTAINER memory.usage_in_bytes 2> /dev/null)
# Report an unknown value if the container is not currently running
[[ -z "$tmp_v" ]] && tmp_v='U'
echo 'mem_usage.value '$tmp_v
   
tmp_v=$($f_comm -n $CONTAINER memory.stat 2> /dev/null | grep total_cache | cut -d ' ' -f 2)
[[ -z "$tmp_v" ]] && tmp_v='U'
echo  'mem_cache.value '$tmp_v
   
tmp_v=$($f_comm -n $CONTAINER memory.stat 2> /dev/null | grep total_active_anon | cut -d ' ' -f 2)
[[ -z "$tmp_v" ]] && tmp_v='U'
echo  'mem_active.value '$tmp_v
   
tmp_v=$($f_comm -n $CONTAINER memory.stat 2> /dev/null | grep total_inactive_anon | cut -d ' ' -f 2)
[[ -z "$tmp_v" ]] && tmp_v='U'
echo  'mem_inactive.value '$tmp_v
