#!/bin/sh

: << =cut

=head1 NAME

lxc_cpu - Plugin to monitor LXC CPU usage

=head1 CONFIGURATION

  [lxc_*]
    user root

=head1 INTERPRETATION

This plugin needs root privilege.

=head1 AUTHOR

vajtsz  vajtsz@gmail.com
mitty   mitty@mitty.jp
alpha_one_x86   alpha_one_x86@firt-world.info

=head1 LICENSE

Unknown license

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

#don't use lxc-ls + ls-info + RUNNING: huge performance improvements 8s -> 0.01s
guest_names=`find /sys/fs/cgroup/cpuacct/lxc/ -maxdepth 1 -mindepth 1 -type d -printf '%f\n' | sort -u`

f_comm='lxc-cgroup  '

if [ "$1" = "autoconf" ]; then
	if [ -r /proc/stat ]; then
		echo yes
		exit 0
	else
		echo "no (no /proc/stat)"
		exit 0
	fi
fi

if [ "$1" = "config" ]; then

 echo 'graph_title CPU User Usage '
 echo 'graph_args -l 0 --base 1000'
 echo 'graph_vlabel USER_HZ'
 echo 'graph_category lxc'

 
 for guest_name in $guest_names;
 do 
  guest="$(clean_fieldname $guest_name)"
  echo 'cpu_user_'$guest'.label '$guest_name
  echo 'cpu_user_'$guest'.type DERIVE'
  echo 'cpu_user_'$guest'.min 0'
 done
 exit 0
fi

 for guest_name in $guest_names;
 do
  guest="$(clean_fieldname $guest_name)"
  echo -n 'cpu_user_'$guest'.value '
  cat /sys/fs/cgroup/cpuacct/lxc/$guest_name/cpuacct.stat | grep user | awk '{print($2)}'

 done


