#!/usr/bin/perl -w

=head1 NAME

Monitor CyberPower UPS Battery Status.


=head1 AUTHOR

Kai Boenke

=head1 LICENSE

Attribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0)

=back


#####
# Enable SNMP-Discovery
###
=head1 MAGIC MARKERS
  #%# family=snmpauto
  #%# capabilities=snmpconf
=cut
if (defined $ARGV[0] and $ARGV[0] eq "snmpconf") {
	print "require 1.3.6.1.2.1.33.1.2.4.0\n";
	exit 0;
}


#####
# Initialize
###
use strict;
use Munin::Plugin::SNMP;
my $session	= Munin::Plugin::SNMP->session();


#####
# Declare OIDs
###
use constant oid_cps_battery_runtime	=> ".1.3.6.1.2.1.33.1.2.3.0";
use constant oid_cps_battery_charge	=> ".1.3.6.1.2.1.33.1.2.4.0";
use constant oid_cps_input_voltage	=> ".1.3.6.1.2.1.33.1.3.3.1.3.1";
use constant oid_cps_output_voltage	=> ".1.3.6.1.2.1.33.1.4.4.1.2.1";
use constant oid_cps_output_load	=> ".1.3.6.1.2.1.33.1.4.4.1.5.1";
use constant oid_cps_env_temp		=> ".1.3.6.1.2.1.";
use constant oid_cps_env_humidity	=> ".1.3.6.1.2.1.";


#####
# Config
###
if (defined $ARGV[0] and $ARGV[0] eq "config") {
	my ($host) = Munin::Plugin::SNMP->config_session();
	print "host_name $host\n" unless $host eq 'localhost';
	print "graph_title CyberPower UPS Runtime
graph_info This graph shows expected runtime informatiom.
graph_category ups
graph_vlabel minutes
";
	print "runtime.label Expected runtime
runtime.draw AREA
runtime.type GAUGE
";

	exit 0;
}


#####
# Get Values
###
my $runtime	= $session->get_single(oid_cps_battery_runtime);

if($runtime ne 'U'){
	print "runtime.value ", $runtime, "\n";
}
