#!/bin/bash
# -*- sh -*-

: << =cut

=pod

=encoding UTF-8

=head1 NAME

cake_tin_throughput_ - Plugin to monitor cake's bandwidth utilization

=head1 CONFIGURATION

None needed.

=head1 INTERPRETATION

Cake, also known as sch_cake is a modern bandwidth limiter, which eliminates
buffer bloat over slow links. It's also capable to give flows, hosts and each 
flow of each host a fair part of the avaible bandwidth.

This plugin allows for a monitoring of cake's bandwidth utilization.

=head1 SEE ALSO

Take a look at "man cake" to get more information about cake.

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf suggest

=head1 AUTHORS

RubenKelevra <ruben@vfn-nrw.de>

work based on the tc plugin, authors:
Steve Schnepp <steve.schnepp@gmail.com>,
Samuel Smith <esaym@cpan.org>,
Nye Liu <nyet@nyet.org>

=head1 LICENSE

GPLv2 or later

=cut

DEVICE=${0##*/cake_tin_throughput_}

tc_cake_get_diffserv() {
    /sbin/tc -s qdisc show dev "$DEVICE" | head -n1 | grep -i "diffserv3" > /dev/null
    if [ $? -eq 0 ]; then
        echo 3
    fi
    /sbin/tc -s qdisc show dev "$DEVICE" | head -n1 | grep -i "diffserv4" > /dev/null
    if [ $? -eq 0 ]; then
        echo 4
    fi
    /sbin/tc -s qdisc show dev "$DEVICE" | head -n1 | grep -i "diffserv8" > /dev/null
    if [ $? -eq 0 ]; then
        echo 8
    fi
    return 0
}

tc_cake_get_bandwidth() {
    bandwidth="$(/sbin/tc -s qdisc show dev "$DEVICE" | grep "^ capacity estimate" | sed -e 's/capacity estimate://' | awk '{ print $1 }')"
    convert_bit "$bandwidth"
}

tc_cake_get_bits() {
    bytes="$(/sbin/tc -s qdisc show dev "$DEVICE" | grep "^  bytes" | sed -e 's/bytes//')"
    for e in ${bytes[@]}; do
        bits="$(convert_byte_to_bit $e)"
        echo -en " $bits "
    done
    echo ""
}

convert_byte_to_bit() {
    #convert byte into bit
    echo $1 | awk '{
        bit = $1;
        sub(/[A-Za-z]+$/, "", bit);
        
        bit *= 8;
        
        print bit
    }'
}

convert_bit() {
    #converts Tbit, Gbit, Mbit, Kbit into bit without a unit
    echo $1 | awk '{
        bit = $1;
        sub(/[A-Za-z]+$/, "", bit);
        unit = $1;
        sub(/^[^A-Za-z]+/, "", unit);

        if (unit == "Tbit") {
            bit *= 1000000000000;
        } else if (unit == "Gbit") {
            bit *= 1000000000;
        } else if (unit == "Mbit") {
            bit *= 1000000;
        } else if (unit == "Kbit") {
            bit *= 1000;
        } else if (unit == "bit") {
            bit = bit;
        }
        print bit
    }'
}

case "$1" in
    autoconf)
    if [ -r /proc/net/dev ]; then
        echo yes
        exit 0
    else
        echo "no (/proc/net/dev not found)"
        exit 1
    fi
    ;;
    suggest)
    if [ -r /proc/net/dev ]; then
        ifs="$(awk '
                /^ *(eth|tap|bond|wlan|ath|ra|sw|eno|ens|enp|wlp|wl)[0-9]*/ {
                   split($0, a, /: */);
                   gsub(/^ +/,"",a[1]);
                   if (($2 > 0) || ($10 > 0)) print a[1]; }' /proc/net/dev)"
        cake_ifs=()
        for if in $ifs; do
            qdisc="$(/sbin/tc -s qdisc show dev "$if" | head -n1 | awk '{ print $2 }')"
            if [ "$qdisc" == "cake" ]; then
                cake_ifs+=("$if")
            fi
        done
        echo "$cake_ifs"
    fi
    exit 0
    ;;
    config)
    
    echo "graph_title $DEVICE cake throughput"
    echo 'graph_args --base 1000'
    echo 'graph_vlabel bit per second'
    echo 'graph_category network'
    echo "graph_info This graph shows the bits per second per tin of egress traffic of the $DEVICE network interface as well as the general bandwidth limit."
    
    diffserv_no="$(tc_cake_get_diffserv)"
    
    if [ "$diffserv_no" == "3" ]; then

        echo "bandwidth.label Bandwidth-Limit"
        echo "bandwidth.type GAUGE"
        echo "bandwidth.min 0"
        echo "bandwidth.info maximal bandwidth set for cake"

        echo "bulk.label Bulk"
        echo "bulk.draw AREA"
        echo "bulk.type DERIVE"
        echo "bulk.min 0"
        echo "bulk.info sent bulk bits thru cake"
        
        echo "besteffort.label Best Effort"
        echo "besteffort.draw STACK"
        echo "besteffort.type DERIVE"
        echo "besteffort.min 0"
        echo "besteffort.info sent best effort bits thru cake"
        
        echo "voice.label Voice"
        echo "voice.draw STACK"
        echo "voice.type DERIVE"
        echo "voice.min 0"
        echo "voice.info sent Voice bits thru cake"
        
        exit 0
    fi
    
    if [ "$diffserv_no" == "4" ]; then
        
        echo "bandwidth.label Bandwidth-Limit"
        echo "bandwidth.type GAUGE"
        echo "bandwidth.min 0"
        echo "bandwidth.info maximal bandwidth set for cake"
        
        echo "bulk.label Bulk"
        echo "bulk.draw AREA"
        echo "bulk.type DERIVE"
        echo "bulk.min 0"
        echo "bulk.info sent bulk bits thru cake"
        
        echo "besteffort.label Best Effort"
        echo "besteffort.draw STACK"
        echo "besteffort.type DERIVE"
        echo "besteffort.min 0"
        echo "besteffort.info sent best effort bits thru cake"
        
        echo "video.label Video"
        echo "video.draw STACK"
        echo "video.type DERIVE"
        echo "video.min 0"
        echo "video.info sent Video bits thru cake"
        
        echo "voice.label Voice"
        echo "voice.draw STACK"
        echo "voice.type DERIVE"
        echo "voice.min 0"
        echo "voice.info sent Voice bits thru cake"
        
        exit 0
    fi
    
    if [ "$diffserv_no" == "8" ]; then
        
        echo "bandwidth.label Bandwidth-Limit"
        echo "bandwidth.type GAUGE"
        echo "bandwidth.min 0"
        echo "bandwidth.info maximal bandwidth set for cake"
        
        echo "tin1.label Tin 1"
        echo "tin1.draw AREA"
        echo "tin1.type DERIVE"
        echo "tin1.min 0"
        echo "tin1.info sent Tin 1 bits thru cake"
        
        for i in `seq 2 8`; do
            echo "tin${i}.label Tin $i"
            echo "tin${i}.draw STACK"
            echo "tin${i}.type DERIVE"
            echo "tin${i}.min 0"
            echo "tin${i}.info sent Tin $i bits thru cake"
        done
        
        exit 0  
    fi
    
    echo "cake_tin: no diffserv set (besteffort?)" >&2
    echo 1
    
    ;;
esac


diffserv_no="$(tc_cake_get_diffserv)"

echo "bandwidth.value $(tc_cake_get_bandwidth)"

### FIXME ###

if [ "$diffserv_no" == "3" ]; then
    tc_cake_get_bits | awk '{
    print "bulk.value " $1
    print "besteffort.value " $2
    print "voice.value " $3
    }'
    exit 0
fi
if [ "$diffserv_no" == "4" ]; then
    tc_cake_get_bits | awk '{
    print "bulk.value " $1
    print "besteffort.value " $2
    print "video.value " $3
    print "voice.value " $4
    }'
    exit 0
fi
if [ "$diffserv_no" == "8" ]; then
    tc_cake_get_bits | awk '{
    print "tin1.value " $1
    print "tin2.value " $2
    print "tin3.value " $3
    print "tin4.value " $4
    print "tin5.value " $5
    print "tin6.value " $6
    print "tin7.value " $7
    print "tin8.value " $8
    }'
    exit 0
fi

### / FIXME ###
exit 1

 
 
 
 
 
