#!/bin/bash
# -*- sh -*-

: << =cut

=pod

=encoding UTF-8

=head1 NAME

cake_tin_throughput_ - Plugin to monitor cake's bandwidth utilization

=head1 CONFIGURATION

None needed.

=head1 INTERPRETATION

Cake, also known as sch_cake is a modern bandwidth limiter, which eliminates
buffer bloat over slow links. It's also capable to give flows, hosts and each 
flow of each host a fair part of the avaible bandwidth.

This plugin allows for a monitoring of cake's bandwidth utilization.

=head1 SEE ALSO

Take a look at "man cake" to get more information about cake.

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf suggest

=head1 AUTHORS

RubenKelevra <ruben@vfn-nrw.de>

work based on the tc plugin, authors:
Steve Schnepp <steve.schnepp@gmail.com>,
Samuel Smith <esaym@cpan.org>,
Nye Liu <nyet@nyet.org>

=head1 LICENSE

GPLv2 or later

=cut

DEVICE=${0##*/cake_tin_throughput_}

tc_get_ifb_dev() {
	dev="$(/sbin/tc filter show dev $DEVICE parent ffff: protocol all | grep "mirred" | grep "Egress Redirect to device")"
	[ $? -eq 1 ] && return 1
	
	echo "$dev" | sed -n 's/.* device \([^ ]*\).*/\1/p' | tr ')' ' ' | awk '{ print $1 }'
}

tc_cake_get_diffserv() {
	/sbin/tc -s qdisc show dev "$1" | head -n1 | grep -i "diffserv3" > /dev/null
	if [ $? -eq 0 ]; then
		echo 3
	fi
	/sbin/tc -s qdisc show dev "$1" | head -n1 | grep -i "diffserv4" > /dev/null
	if [ $? -eq 0 ]; then
		echo 4
	fi
	/sbin/tc -s qdisc show dev "$1" | head -n1 | grep -i "diffserv8" > /dev/null
	if [ $? -eq 0 ]; then
		echo 8
	fi
	return 0
}

tc_cake_get_bandwidth() {
	bandwidth="$(/sbin/tc -s qdisc show dev "$1" | grep "^ capacity estimate" | sed -e 's/capacity estimate://' | awk '{ print $1 }')"
	convert_bit "$bandwidth"
}

tc_cake_get_bits() {
	bytes="$(/sbin/tc -s qdisc show dev "$1" | grep "^  bytes" | sed -e 's/bytes//')"
	for e in ${bytes[@]}; do
		bits="$(convert_byte_to_bit $e)"
		echo -en " $bits "
	done
	echo ""
}

convert_byte_to_bit() {
	#convert byte into bit
	echo $1 | awk '{
		bit = $1;
		sub(/[A-Za-z]+$/, "", bit);
		
		bit *= 8;
		
		print bit
	}'
}

convert_bit() {
	#converts Tbit, Gbit, Mbit, Kbit into bit without a unit
	echo $1 | awk '{
		bit = $1;
		sub(/[A-Za-z]+$/, "", bit);
		unit = $1;
		sub(/^[^A-Za-z]+/, "", unit);

		if (unit == "Tbit") {
			bit *= 1000000000000;
		} else if (unit == "Gbit") {
			bit *= 1000000000;
		} else if (unit == "Mbit") {
			bit *= 1000000;
		} else if (unit == "Kbit") {
			bit *= 1000;
		} else if (unit == "bit") {
			bit = bit;
		}
		print bit
	}'
}

DEVICE_IN="$(tc_get_ifb_dev)"
has_if_in=$?

diffserv_no="$(tc_cake_get_diffserv "$DEVICE")"
if [ $has_if_in -eq 0 ]; then
	diffserv_in_no="$(tc_cake_get_diffserv "$DEVICE_IN")"
	
	if [ ! "$diffserv_no" == "$diffserv_in_no" ]; then
		echo "cake_tin_throughput_: diffserv setting different between egress and ingress device - this cannot be plotted, exiting" >&2
		exit 1
	fi
fi

case "$1" in
	autoconf)
	if [ -r /proc/net/dev ]; then
		echo yes
		exit 0
	else
		echo "no (/proc/net/dev not found)"
		exit 1
	fi
	;;
	suggest)
	if [ -r /proc/net/dev ]; then
		ifs="$(awk '
				/^ *(eth|tap|bond|wlan|ath|ra|sw|eno|ens|enp|wlp|wl)[0-9]*/ {
				   split($0, a, /: */);
				   gsub(/^ +/,"",a[1]);
				   if (($2 > 0) || ($10 > 0)) print a[1]; }' /proc/net/dev)"
		cake_ifs=()
		for if in $ifs; do
			qdisc="$(/sbin/tc -s qdisc show dev "$if" | head -n1 | awk '{ print $2 }')"
			if [ "$qdisc" == "cake" ]; then
				cake_ifs+=("$if")
			fi
		done
		echo "$cake_ifs"
	fi
	exit 0
	;;
	config)
	
	if [ $has_if_in -eq 0 ]; then
		echo "graph_title $DEVICE ($DEVICE_IN) cake throughput"
	else
		echo "graph_title $DEVICE cake throughput"
	fi
	echo 'graph_args --base 1000'
	if [ $has_if_in -eq 0 ]; then
		echo 'graph_vlabel bit/s in (-) / out (+)'
	else
		echo 'graph_vlabel  bit/s'
	fi
	echo 'graph_category network'
	if [ $has_if_in -eq 0 ]; then
		echo "graph_info This graph shows the bits per second per tin of egress+ingress traffic of the $DEVICE ($DEVICE_IN) network interface as well as the general bandwidth limit."
	else
		echo "graph_info This graph shows the bits per second per tin of egress traffic of the $DEVICE network interface as well as the general bandwidth limit."
	fi
	
	if [ "$diffserv_no" == "3" ]; then
		
		if [ $has_if_in -eq 0 ]; then
			echo "bandwidth_in.label Bandwidth-Limit"
			echo "bandwidth_in.type GAUGE"
			echo "bandwidth_in.min 0"
			echo "bandwidth_in.info maximal bandwidth set for cake"
			echo "bandwidth_in.graph no"
		fi
		echo "bandwidth.label Bandwidth-Limit"
		echo "bandwidth.type GAUGE"
		echo "bandwidth.min 0"
		echo "bandwidth.info maximal bandwidth set for cake"
		[ $has_if_in -eq 0 ] && echo "bandwidth.negative bandwidth_in"

		if [ $has_if_in -eq 0 ]; then
			echo "bulk_in.label Bulk"
			echo "bulk_in.type DERIVE"
			echo "bulk_in.min 0"
			echo "bulk_in.info sent Bulk bits thru cake"
			echo "bulk_in.graph no"
		fi
		echo "bulk.label Bulk"
		echo "bulk.type DERIVE"
		echo "bulk.min 0"
		echo "bulk.info sent Bulk bits thru cake"
		[ $has_if_in -eq 0 ] && echo "bulk.negative bulk_in"
		
		if [ $has_if_in -eq 0 ]; then
			echo "besteffort_in.label Best Effort"
			echo "besteffort_in.type DERIVE"
			echo "besteffort_in.min 0"
			echo "besteffort_in.info sent Best Effort bits thru cake"
			echo "besteffort_in.graph no"
		fi
		echo "besteffort.label Best Effort"
		echo "besteffort.type DERIVE"
		echo "besteffort.min 0"
		echo "besteffort.info sent Best Effort bits thru cake"
		[ $has_if_in -eq 0 ] && echo "besteffort.negative besteffort_in"
		
		if [ $has_if_in -eq 0 ]; then
			echo "voice_in.label Voice"
			echo "voice_in.type DERIVE"
			echo "voice_in.min 0"
			echo "voice_in.info sent Voice bits thru cake"
			echo "voice_in.graph no"
		fi
		echo "voice.label Voice"
		echo "voice.type DERIVE"
		echo "voice.min 0"
		echo "voice.info sent Voice bits thru cake"
		[ $has_if_in -eq 0 ] && echo "voice.negative voice_in"
		
		exit 0
	fi
	
	if [ "$diffserv_no" == "4" ]; then
		
		if [ $has_if_in -eq 0 ]; then
			echo "bandwidth_in.label Bandwidth-Limit"
			echo "bandwidth_in.type GAUGE"
			echo "bandwidth_in.min 0"
			echo "bandwidth_in.info maximal bandwidth set for cake"
			echo "bandwidth_in.graph no"
		fi
		echo "bandwidth.label Bandwidth-Limit"
		echo "bandwidth.type GAUGE"
		echo "bandwidth.min 0"
		echo "bandwidth.info maximal bandwidth set for cake"
		[ $has_if_in -eq 0 ] && echo "bandwidth.negative bandwidth_in"

		if [ $has_if_in -eq 0 ]; then
			echo "bulk_in.label Bulk"
			echo "bulk_in.type DERIVE"
			echo "bulk_in.min 0"
			echo "bulk_in.info sent Bulk bits thru cake"
			echo "bulk_in.graph no"
		fi
		echo "bulk.label Bulk"
		echo "bulk.type DERIVE"
		echo "bulk.min 0"
		echo "bulk.info sent Bulk bits thru cake"
		[ $has_if_in -eq 0 ] && echo "bulk.negative bulk_in"
		
		if [ $has_if_in -eq 0 ]; then
			echo "besteffort_in.label Best Effort"
			echo "besteffort_in.type DERIVE"
			echo "besteffort_in.min 0"
			echo "besteffort_in.info sent Best Effort bits thru cake"
			echo "besteffort_in.graph no"
		fi
		echo "besteffort.label Best Effort"
		echo "besteffort.type DERIVE"
		echo "besteffort.min 0"
		echo "besteffort.info sent Best Effort bits thru cake"
		[ $has_if_in -eq 0 ] && echo "besteffort.negative besteffort_in"
		
		if [ $has_if_in -eq 0 ]; then
			echo "video_in.label Video"
			echo "video_in.draw STACK"
			echo "video_in.type DERIVE"
			echo "video_in.min 0"
			echo "video_in.info sent Video bits thru cake"
			echo "video_in.graph no"
		fi
		echo "video.label Video"
		echo "video.draw STACK"
		echo "video.type DERIVE"
		echo "video.min 0"
		echo "video.info sent Video bits thru cake"
		[ $has_if_in -eq 0 ] && echo "video.negative video_in"
		
		if [ $has_if_in -eq 0 ]; then
			echo "voice_in.label Voice"
			echo "voice_in.type DERIVE"
			echo "voice_in.min 0"
			echo "voice_in.info sent Voice bits thru cake"
			echo "voice_in.graph no"
		fi
		echo "voice.label Voice"
		echo "voice.type DERIVE"
		echo "voice.min 0"
		echo "voice.info sent Voice bits thru cake"
		[ $has_if_in -eq 0 ] && echo "voice.negative voice_in"
		
		exit 0
	fi
	
	if [ "$diffserv_no" == "8" ]; then
		
		if [ $has_if_in -eq 0 ]; then
			echo "bandwidth_in.label Bandwidth-Limit"
			echo "bandwidth_in.type GAUGE"
			echo "bandwidth_in.min 0"
			echo "bandwidth_in.info maximal bandwidth set for cake"
			echo "bandwidth_in.graph no"
		fi
		echo "bandwidth.label Bandwidth-Limit"
		echo "bandwidth.type GAUGE"
		echo "bandwidth.min 0"
		echo "bandwidth.info maximal bandwidth set for cake"
		[ $has_if_in -eq 0 ] && echo "bandwidth.negative bandwidth_in"
		
		if [ $has_if_in -eq 0 ]; then
			echo "tin1_in.label Tin 1"
			echo "tin1_in.draw AREA"
			echo "tin1_in.type DERIVE"
			echo "tin1_in.min 0"
			echo "tin1_in.info sent Tin 1 bits thru cake"
			echo "tin1_in.graph no"
		fi
		echo "tin1.label Tin 1"
		echo "tin1.draw AREA"
		echo "tin1.type DERIVE"
		echo "tin1.min 0"
		echo "tin1.info sent Tin 1 bits thru cake"
		[ $has_if_in -eq 0 ] && echo "tin1.negative tin1_in"
		
		for i in `seq 2 8`; do
			if [ $has_if_in -eq 0 ]; then
				echo "tin${i}_in.label Tin $i"
				echo "tin${i}_in.draw STACK"
				echo "tin${i}_in.type DERIVE"
				echo "tin${i}_in.min 0"
				echo "tin${i}_in.info sent Tin $i bits thru cake"
				echo "tin${i}_in.graph no"
			fi
			echo "tin${i}.label  Tin $i"
			echo "tin${i}.draw STACK"
			echo "tin${i}.type DERIVE"
			echo "tin${i}.min 0"
			echo "tin${i}.info sent Tin $i bits thru cake"
			[ $has_if_in -eq 0 ] && echo "tin${i}.negative tin${i}_in"
		done
		
		exit 0  
	fi
	
	echo "cake_tin_throughput_: no diffserv or unknown parameter set (best effort?)" >&2
	exit 1
	
	;;
esac

if [ "$diffserv_no" == "3" ]; then
	echo "bandwidth.value $(tc_cake_get_bandwidth $DEVICE)"

	tc_cake_get_bits "$DEVICE" | awk '{
	print "bulk.value " $1
	print "besteffort.value " $2
	print "voice.value " $3
	}'
	
	if [ $has_if_in -eq 0 ]; then
		echo "bandwidth_in.value $(tc_cake_get_bandwidth $DEVICE_IN)"
		
		tc_cake_get_bits "$DEVICE_IN" | awk '{
		print "bulk_in.value " $1
		print "besteffort_in.value " $2
		print "voice_in.value " $3
		}'
	fi
	exit 0
fi
if [ "$diffserv_no" == "4" ]; then
	echo "bandwidth.value $(tc_cake_get_bandwidth $DEVICE)"
	
	tc_cake_get_bits "$DEVICE" | awk '{
	print "bulk.value " $1
	print "besteffort.value " $2
	print "video.value " $3
	print "voice.value " $4
	}'
	
	if [ $has_if_in -eq 0 ]; then
		echo "bandwidth_in.value $(tc_cake_get_bandwidth $DEVICE_IN)"
		
		tc_cake_get_bits "$DEVICE_IN" | awk '{
		print "bulk_in.value " $1
		print "besteffort_in.value " $2
		print "video_in.value " $3
		print "voice_in.value " $4
		}'
	fi
	exit 0
fi
if [ "$diffserv_no" == "8" ]; then
	echo "bandwidth.value $(tc_cake_get_bandwidth $DEVICE)"
	
	tc_cake_get_bits "$DEVICE" | awk '{
	print "tin1.value " $1
	print "tin2.value " $2
	print "tin3.value " $3
	print "tin4.value " $4
	print "tin5.value " $5
	print "tin6.value " $6
	print "tin7.value " $7
	print "tin8.value " $8
	}'
	
	if [ $has_if_in -eq 0 ]; then
		echo "bandwidth_in.value $(tc_cake_get_bandwidth $DEVICE_IN)"
		
		tc_cake_get_bits "$DEVICE_IN" | awk '{
		print "tin1_in.value " $1
		print "tin2_in.value " $2
		print "tin3_in.value " $3
		print "tin4_in.value " $4
		print "tin5_in.value " $5
		print "tin6_in.value " $6
		print "tin7_in.value " $7
		print "tin8_in.value " $8
		}'
	fi
	exit 0
fi

exit 1

 
 
 
 
 
