#!/usr/bin/perl
#
# Copyright (C) 2008 - Nathan Haneysmith <nathan@hjksolutions.com>
# Copyright (C) 2007 - Rodolphe Quiedeville <rodolphe@quiedeville.org>
# Copyright (C) 2003-2004 - Andreas Buer
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2 dated June,
# 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# $Log$
# Revision 1.2 2008/06/18 Nathan Haneysmith
# Massive rewrite to check and graph MySQL Slave status
#
# Revision 1.1  2007/01/17 10:41:01  rodo
# Change incorrect family
#
# Revision 1.0  2007/01/16 15:57:01  rodo
# Created by Rodolphe Quiedeville
#
# Parameters:
#
#   config
#   autoconf
#
# Configuration variables
#
#   mysqlopts     - Options to pass to mysql
#   mysqladmin    - Override location of mysqladmin
#
#%# family=manual
#%# capabilities=autoconf

use strict;

my $MYSQLADMIN = $ENV{mysqladmin} || "mysql";
my $MYSQLOPTS = $ENV{mysqlopts} || "";

my %WANTED = ( "Seconds"  => "seconds", 
             );

my $arg = shift();

if ($arg eq 'config') {
    print_config();
    exit();
} elsif ($arg eq 'autoconf') {
    unless (test_service() ) {
        print "yes\n";
    } else {
        print "no\n";
    }
    exit;
}

my $seconds = 0;
my (@infos,$info,$i_seconds);

my $COMMAND = "$MYSQLADMIN $MYSQLOPTS -e 'show slave status;' | grep 'Slave'";

open(SERVICE, "$COMMAND |")
  or die("Coult not execute '$COMMAND': $!");

while (<SERVICE>) {
    (@infos)  = split;
}
close(SERVICE);

my $i = 0;
foreach $info (@infos) {
    $i++;
    if ($info eq 'Seconds_Behind_Master') {
	$i_seconds = $i;
	next;
    }
}

$COMMAND = "$MYSQLADMIN $MYSQLOPTS -e 'show slave status;' | cut -f $i_seconds | grep -v leng";

open(SERVICE, "$COMMAND |")
  or die("Coult not execute '$COMMAND': $!");

while (<SERVICE>) {
    (m/(\d+).*?(\d+(?:\.\d+)?)/);
    $seconds += $1;
}
close(SERVICE);

print("seconds.value $seconds\n");


sub print_config {

  print "graph_title MySQL Slave Status\n";
  print "graph_args --base 1000 -l 0\n";
  print "graph_vlabel Seconds\n";
  print "graph_category mysql\n";
  print "seconds.label Seconds behind master\n";
  print "seconds.min 0\n";
  print "seconds.draw LINE2\n";
  print "graph_info Plugin available at <a href='http://oss.hjksolutions.com/munin/'>http://oss.hjksolutions.com/munin/</a>\n";

}


sub test_service {

    my $return = 1;

    system ("$MYSQLADMIN --version >/dev/null 2>/dev/null");
    if ($? == 0)
    {
	system ("$COMMAND >/dev/null 2>/dev/null");
	if ($? == 0)
	{
	    print "yes\n";
	    $return = 0;
	}
	else
	{
	    print "no (could not connect to mysql)\n";
	}
    }
    else
    {
	print "no (mysqladmin not found)\n";
    }
    exit $return;
}
