#!/usr/bin/perl
# Munin plugin for MySQL slave threads monitoring
# Copyright © 2009 Eutech SSII
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Plugin producing state graphes for a MySQL slave server (1 if
# I/O or SQL thread is running, 0 otherwise). Can be used to
# trigger a warning when a replication failure occurs.

use strict;

my $MYSQL = $ENV{mysql} || "mysql";
my $MYSQLOPTS = $ENV{mysqlopts} || "";

if(defined $ARGV[0] && $ARGV[0] eq 'config') {
    print <<EOC
graph_title MySQL Slave Threads
graph_vlabel Running
graph_category db
graph_args -l 0
io.label I/O Thread
io.critical 1:1
sql.label SQL Thread
sql.critical 1:1
EOC
;
        exit 0;
}

my $status = `$MYSQL $MYSQLOPTS -e 'SHOW SLAVE STATUS\\G'`;

$status =~ /Slave_IO_Running: (\w+)/; 
print 'io.value '.($1 eq 'Yes' ? 1 : 0)."\n";
$status =~ /Slave_SQL_Running: (\w+)/;
print 'sql.value '.($1 eq 'Yes' ? 1 : 0)."\n";


