#!/bin/sh

#Author Juned Memon www.tipsNtrapS.com (juned.memon@tipsntraps.com)

#To Check how stable the Hadoop filesystem is, we generally check number of under-replicated nodes in hadoop. This plugin graphs the under-replicated nodes in hadoop.

case $1 in
   config)
        cat <<'EOM'
graph_title Under Replicated Blocks Hadoop
graph_category fs
graph_vlabel block
block.label block
EOM
        exit 0;;
esac

echo -n "block.value "
hadoop dfsadmin -report | grep "Under replicated blocks" | awk '{print $4}'
