#!/usr/bin/php
# Author David Gagnon <djgagnon@wisc.edu>
# Plugin to monitor ARIS users
#
# Parameters:
#
# 	config   (required)
# 	
#
#%# family=manual


<?php
$aris_db_host='localhost';
$aris_db_name='db';
$aris_db_user='user';
$aris_db_pass='password';

if ($argv[1]=='config'){
    print "graph_title ARIS active players\n";
    print "graph_vlabel Players Count\n";
    print "graph_category ARIS\n";
    print "players.label player count\n";

    exit;
}

$sqlLink = mysql_connect($aris_db_host,$aris_db_user,$aris_db_pass) or die('MySQL authenticaiton error');
mysql_select_db($aris_db_name) or die('MySQL Wrong Scheme Error');

    $query = 'SELECT COUNT(DISTINCT player_id) AS count FROM player_log WHERE timestamp BETWEEN DATE_SUB(NOW(), INTERVAL 5 MINUTE) AND NOW()';
    $result = mysql_query($query);
    $numCurrentPlayersObject = mysql_fetch_object($result);
    $numCurrentPlayers = $numCurrentPlayersObject->count;

echo 'players.value '. $numCurrentPlayers;

?>
