#!/bin/sh
#
#  pdns_recursor munin plugin.
#  Written by Sean Reifschneider <jafo@tummy.com> 2009-12-03
#  Placed in the public domain
#
#  Requires running as root:
#
#    echo '[pdns_rec_*]' >/etc/munin/plugin-conf.d/pdns_rec
#    echo 'user root' >>/etc/munin/plugin-conf.d/pdns_rec

if [ "$1" = "autoconf" ]; then
	if [ -e /usr/bin/rec_control ]; then
		echo yes
		exit 0
	else
		echo no
		exit 1
	fi
fi

if [ "$1" = "config" ]; then
	echo 'graph_title PDNS Recursor Answer Latency'
	echo 'graph_order latency'
	echo 'graph_vlabel ms'
	echo 'graph_info Question latency'
	echo 'graph_category pdns'

	echo 'latency.label ms'
	echo 'latency.min 0'
	echo 'latency.type GAUGE'
	echo 'latency.info Answer latency'

	exit 0
fi

echo latency.value `rec_control get qa-latency`

exit 0
