#!/bin/sh


: <<=cut

=head1 NAME

bandwidth_ - Plugin to monitor the bandwidth between localhost and another host.

=head1 APPLICABLE SYSTEMS

All systems with “bash”, and “munin”

=head1 REQUIREMENTS

bing installed.

You can install bing by using (Ubuntu/Debian): apt-get install bing

=head1 CONFIGURATION

The following is the default configuration

[bandwidth_*]
user root
env.samples 10
env.small_packet_size 1000
env.big_packet_size 8000

- env.samples explanation: Reset stats after sending samples ECHO_REQUEST packets.

- env.small_packet_size explanation: Specifies the number of data bytes to be sent in the small packets. The default and minimum value is 44.

- env.big_packet_size explanation: Specifies the number of data bytes to be sent in the big packets. The default is 108. The size should be chosen so that big packet roundtrip times are long enough to be accurately measured.


You need to do the symlink by adding the host with which you want to check the bandwidth after the "_". Example:
ln -s /usr/share/munin/plugins/bandwidth_ /etc/munin/plugins/bandwidth_example.org


=head1 MAGIC MARKERS

#%# capabilities=autoconf

=head1 VERSION

1.1.24

=head1 AUTHOR

Jose Manuel Febrer Cortés <https://www.linkedin.com/in/jfebrer/>
Marco Bertola’s help <https://www.linkedin.com/in/bertolamarco/>

=head1 LICENSE

GPLv2

=cut


host="$(basename "$0" | cut -d"_" -f2)"
case $1 in
   config)
                echo graph_title Bandwidth
                echo 'graph_vlabel Mbps'
                echo 'graph_args --base 1000 -l 0'
                echo 'graph_scale no'
                echo 'graph_category network'
                echo 'graph_info This graph shows the bandwidth between localhost and ' "$host"
                echo 'bandwidth.info Bandwidth statistics for ' "$host"
                echo 'bandwidth.label ' "$host"
        exit 0;;
   autoconf)
        if hash bing 2>/dev/null; then
                echo 'yes'
                exit 0;
        else
                echo 'no (bing not installed)'
                exit 0;
        fi
esac


#Calculating the bandwidth
printf "bandwidth.value ";
#bing output example: host:  4.592Mbps 0.223ms 0.217773us/bit
bing localhost "$host" -n -c 1 -e "$samples" -s "$small_packet_size" -S "$big_packet_size" 2>/dev/null \
        | grep -E "bit$" \
        | awk -F" +" '{ print $2}' | cut -c -5 \
        | cut -c -5 \
        | awk '{a+=$1} END{print a/NR}'

