#!/usr/bin/perl -w

# Author : Alban Espie-Guillon <alban.espie@alterway.fr>
# Based on http://github.com/perusio/nginx-munin Author: António P. P. Almeida <appa@perusio.net>

# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# Except as contained in this notice, the name(s) of the above copyright
# holders shall not be used in advertising or otherwise to promote the sale,
# use or other dealings in this Software without prior written authorization.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

=head1 NAME

mongodb_cpu - Munin plugin to show CPU used by mongodb.

=encoding utf8

=head1 APPLICABLE SYSTEMS

Any mongodb host

=head1 MAGIC MARKERS

  #%# family=auto
  #%# capabilities=autoconf

=head1 VERSION

1.0

=head1 BUGS

None known

=head1 AUTHOR

Based on a script by António P. P. Almeida <appa@perusio.net>. Modified by Alban Espie-Guillon <alban.espie@alterway.fr>

=head1 LICENSE

MIT

=cut

## Munin config method.
if (exists $ARGV[0] and $ARGV[0] eq "config") {
  print "graph_title Mongodb CPU usage\n";
  print "graph_vlabel CPU\n";
  print "graph_category db\n";
  print "graph_args --base 1000 -r --lower-limit 0\n";
  print "graph_scale no\n";
  print "graph_period second\n";
  print "cpu.label CPU\n";
  print "cpu.type GAUGE\n";
  print "cpu.draw AREASTACK\n";
  print "cpu.min 0\n";
  exit 0;
} else {
  my $c = `ps u -p  \$(pidof mongod) | awk 'NR > 1 {print \$3}'`;
  print "cpu.value $c";
}
