#!/bin/bash
# -*- bash -*-

: << =cut

=head1 NAME

haproxy_aborts_backend -Haproxy Aborts Backend

=head1 CONFIGURATION

[haproxy*]
  user root
  env.backend backend_name_1 backend_name_2 backend_name_3
  env.frontend frontend_name_1 frontend_name_2 frontend_name_3
  # You can use url o socket option, use one of them, not both!
    env.url  http://user:passwd@IP:port/admin?stats;csv
  #  or
    env.socket /var/lib/haproxy/stats.socket

=head1 AUTHOR

Ricardo Fraile <rfrail3@yahoo.es>

=head1 LICENSE

GPLv2

=head1 MAGICK MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

function parse_url {
        # Modify ifs variable
        OIFS=$IFS;
        IFS=",";
        PXNAME="$1"
        SVNAME="$2"
        VALUE="$3"

	if [ ! -z "$url" ]; then
		LINE1=`curl -s "$url" | head -1 | sed 's/# //'`
	        LINE2=`curl -s "$url" | grep "$PXNAME,$SVNAME"`
        fi

	if [ ! -z "$socket" ]; then
                LINE1=`echo 'show stat' | socat unix-connect:"$socket" stdio | head -1 | sed 's/# //'`
                LINE2=`echo 'show stat' | socat unix-connect:"$socket" stdio | grep "$PXNAME,$SVNAME"`         
        fi
        
        ARRAY1=($LINE1);

        # Find values
        for ((i=0; i<${#ARRAY1[@]}; ++i));
        do
                # Get data
                if [[ "${ARRAY1[$i]}" == "${VALUE}" ]]; then
                        o=$i;
                        o=`expr $o + 1`
                        echo ${LINE2} | cut -d" " -f $o
                fi
        done

        # Reset ifs
        IFS=$OIFS;
}


SVNAME='BACKEND'
LIST="$backend"


if [ "$1" = "autoconf" ]; then
	echo yes 
	exit 0
fi

if [ "$1" = "config" ]; then

	echo "graph_title Aborts ${SVNAME}"
	echo 'graph_args --base 1000 -l 0 '
	echo 'graph_vlabel Aborts'
	echo 'graph_scale no'
	echo 'graph_category loadbalancer'
	echo "graph_info Aborts ${SVNAME}"


	for i in ${LIST}; do
	        echo "cli_abrt`echo $i | md5sum | cut -d - -f1 | sed 's/ //g'`.label Aborted by client $i"
        	echo "cli_abrt`echo $i | md5sum | cut -d - -f1 | sed 's/ //g'`.type DERIVE"
	        echo "cli_abrt`echo $i | md5sum | cut -d - -f1 | sed 's/ //g'`.min 0"
        	echo "cli_abrt`echo $i | md5sum | cut -d - -f1 | sed 's/ //g'`.info Data transfers aborted by the client $i"

	        echo "srv_abrt`echo $i | md5sum | cut -d - -f1 | sed 's/ //g'`.label Aborted by server $i"
        	echo "srv_abrt`echo $i | md5sum | cut -d - -f1 | sed 's/ //g'`.type DERIVE"
	        echo "srv_abrt`echo $i | md5sum | cut -d - -f1 | sed 's/ //g'`.min 0"
        	echo "srv_abrt`echo $i | md5sum | cut -d - -f1 | sed 's/ //g'`.info Data transfers aborted by the server $i"

	done

	exit 0
fi
	for i in ${LIST}; do
		CLI=`parse_url ${i} ${SVNAME} cli_abrt`
		SRV=`parse_url ${i} ${SVNAME} srv_abrt`

	        echo "cli_abrt`echo $i | md5sum | cut -d - -f1 | sed 's/ //g'`.value $CLI"
	        echo "srv_abrt`echo $i | md5sum | cut -d - -f1 | sed 's/ //g'`.value $SRV"
	done
	

