#!/usr/bin/env python
"""
munin US NOAA weather plugin (http://tgftp.nws.noaa.gov)

Draws temperature/dew point in C.
Copy/link file as 'weather_temp_CODE', like: weather_temp_LOWW for Austria, Vienna.

Get the code by going to http://tgftp.nws.noaa.gov, selecting your
location, and copying the code from the address bar of your browser; should
be something like CODE.html.

Linux users might need to adjust the shebang.
"""

import sys
import urllib
import re

url = 'http://tgftp.nws.noaa.gov/data/observations/metar/decoded/%s.TXT'

re_C = re.compile('Temperature:.*\((-?\d+\.?\d?) C\)')
re_DewC = re.compile('Dew.*\((-?\d+\.?\d?) C\)')

code = sys.argv[0][(sys.argv[0].rfind('_')+1):]
if code == None: sys.exit(1)

if len(sys.argv) == 2 and sys.argv[1] == "autoconf":

  print "yes"

elif len(sys.argv) == 2 and sys.argv[1] == "config":

  print 'graph_title Temperature and Dew Point at code %s' % code
  print 'graph_vlabel Temperature and Dew Point in C'
  print 'graph_category Weather'

  print 'temperature.label Temperature'
  print 'dewpoint.label Dew Point'

  print 'graph_args --base 1000 -l 0'

else:

  u = urllib.urlopen(url % code)
  txt = u.read()
  u.close()

  C = re_C.findall(txt)[0]
  DewC = re_DewC.findall(txt)[0]

  print 'temperature.value %s' % C
  print 'dewpoint.value %s' % DewC

