#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

nextcloud-serverinfo_ - Plugin to monitor Nextcloud's serverinfo statut

=head1 CONFIGURATION

  [nextcloud-serverinfo_*]
    env.serverinfo_url https://cloud.example.net/ocs/v2.php/apps/serverinfo/api/v1/info
    env.serverinfo_login LOGIN
    env.serverinfo_password APP_PASSWORD

=head1 AUTHOR

Olivier Mehani

Copyright (C) 2018 Olivier Mehani <shtrom+munin@ssji.net>

=head1 LICENSE

GPLv3+

=cut

# shellcheck disable=SC1090
. "${MUNIN_LIBDIR}/plugins/plugin.sh"

if [ "${MUNIN_DEBUG}" = 1 ]; then
    set -x
fi

mode="$(echo "$0" | sed 's/.*_//')"
# storage
# share
# server
# system
# webserver php
# database
# activeusers

if ! which curl >/dev/null; then
	echo "curl not found" >&2
	exit 1
fi
if ! which xpath >/dev/null; then
	echo "xpath (Perl XML::LibXML) not found" >&2
	exit 1
fi

METRICS="
/ocs/data/nextcloud/system/version
/ocs/data/nextcloud/system/freespace
/ocs/data/nextcloud/system/cpuload/element[1]
/ocs/data/nextcloud/system/mem_total
/ocs/data/nextcloud/system/mem_free
/ocs/data/nextcloud/system/swap_total
/ocs/data/nextcloud/system/swap_free
/ocs/data/nextcloud/storage/num_users
/ocs/data/nextcloud/storage/num_files
/ocs/data/nextcloud/storage/num_storages_local
/ocs/data/nextcloud/storage/num_storages_home
/ocs/data/nextcloud/storage/num_storages_other
/ocs/data/nextcloud/shares/num_shares
/ocs/data/nextcloud/shares/num_shares_user
/ocs/data/nextcloud/shares/num_shares_groups
/ocs/data/nextcloud/shares/num_shares_link
/ocs/data/nextcloud/shares/num_shares_link_no_password
/ocs/data/nextcloud/shares/num_fed_shares_sent
/ocs/data/nextcloud/shares/num_fed_shares_received
/ocs/data/server/webserver
/ocs/data/server/php/version
/ocs/data/server/php/memory_limit
/ocs/data/server/php/max_execution_time
/ocs/data/server/php/upload_max_filesize
/ocs/data/server/database/type
/ocs/data/server/database/version
/ocs/data/server/database/size
/ocs/data/activeUsers/last5minutes
/ocs/data/activeUsers/last1hour
/ocs/data/activeUsers/last24hours
"

short_metric() {
	metric="${1}"
	echo "${metric}" | sed 's^.*/^^'
}

case $1 in
    config)

	echo "graph_title Nextcloud serverinfo for ${serverinfo_url}"
	echo 'graph_category nextcloud'
	for metric in $METRICS; do
		fieldname="$(clean_fieldname "$(short_metric "${metric}")")"
		echo "${fieldname}.label ${metric}"
	done

	exit 0
	;;
esac

DATA="$(echo "user=${serverinfo_login}:${serverinfo_password}" | curl -s -K - "${serverinfo_url}")"

for metric in $METRICS; do
    fieldname="$(clean_fieldname "$(short_metric "${metric}")")"
    value=$(echo "${DATA}" | \
	    xpath -q -n -e "${metric}" | \
	    sed 's/<\([^>]*\)>\([^<]*\)<[^>]*>/\2/')
    printf "%s.value %s\\n" "${fieldname}" "${value}"
done
