#!/bin/sh
: <<=cut
=head1 NAME
strelaysrv_ - Plugin to monitor Syncthing relay server

=head1 DESCRIPTION
This plugin gathers metrics from a Syncthing relay server.

This plugin requires the jq utility : https://stedolan.github.io/jq/

Available plugins :
strelaysrv_goroutine #
strelaysrv_num       # 
strelaysrv_transfer  #
strelaysrv_uptime    #

=head1 CONFIGURATION
To make the plugin connect to the Syncthing relay server one has to use this type of 
configuration
[strelaysrv_*]

env.STR_HOST 127.0.0.1
env.STR_PORT 22070

=head1 AUTHOR
Pierre-Alain TORET <pierre-alain.toret@protonmail.com>

=head1 LICENSE
MIT
=cut

function num {
    case $1 in
       config)
            cat <<'EOM'
graph_title Syncthing relay numbers
graph_category network
graph_vlabel numbers
strelaysrv_num_sessions.label sessions
strelaysrv_num_connections.label connections
strelaysrv_num_pending.label pending session keys
strelaysrv_num_proxies.label proxies
EOM
        exit 0;;
        *)
            NS=$(curl -s http://$STR_HOST:$STR_PORT/status | jq '.numActiveSessions ')
            NC=$(curl -s http://$STR_HOST:$STR_PORT/status | jq '.numConnections ')
            NK=$(curl -s http://$STR_HOST:$STR_PORT/status | jq '.numPendingSessionKeys ')
            NP=$(curl -s http://$STR_HOST:$STR_PORT/status | jq '.numProxies ')
            printf "strelaysrv_num_sessions.value $NS\nstrelaysrv_num_connections.value $NC\nstrelaysrv_num_pending.value $NK\nstrelaysrv_num_proxies.value $NP\n"
    esac
}

function uptime {
    case $1 in
       config)
            cat <<'EOM'
graph_title Syncthing relay uptime
graph_vlabel uptime in seconds
graph_category network
strelaysrv_uptime.label uptime
EOM
        exit 0;;
        *)
            printf "strelaysrv_uptime.value "
            curl -s http://$STR_HOST:$STR_PORT/status | jq '.uptimeSeconds' 
    esac
}

function goroutine {
    case $1 in
       config)
            cat <<'EOM'
graph_title Syncthing relay go routines
graph_vlabel number of go routines
graph_category network
strelaysrv_goroutine.label routines 
EOM
        exit 0;;
        *)
printf "strelaysrv_goroutine.value "
curl -s http://$STR_HOST:$STR_PORT/status | jq '.goNumRoutine'
    esac
}

function transfer {
    case $1 in
       config)
            cat <<'EOM'
graph_title Syncthing relay transfer rate
graph_category network
graph_vlabel bps
graph_args --base 1000
strelaysrv_transfer.label bps
strelaysrv_transfer.cdef strelaysrv_transfer,8000,*
EOM
            exit 0;;
	*)
            printf "strelaysrv_transfer.value "
            curl -s http://$STR_HOST:$STR_PORT/status | jq '.kbps10s1m5m15m30m60m[2] '
    esac
}

cd $(dirname $0)

case $(basename $0) in 
    strelaysrv_num)
	num $1
	exit 0;;
    strelaysrv_uptime)
	uptime $1
	exit 0;;
    strelaysrv_goroutine)
	goroutine $1
	exit 0;;
    strelaysrv_transfer)
	transfer $1
	exit 0;;
esac
