#!/bin/sh
#
# Plugin to monitor yum update activity
#
# Parameters:
#
# 	config
# 	autoconf
#


if [ "$1" = "autoconf" ]; then
	if [ -r /var/log/yum.log ]; then
		echo yes
	else
		echo "no (/var/log/yum.log not readable)"
	fi
	exit 0
fi

if [ "$1" = "config" ]; then

	echo 'graph_title Yum Activity'
	echo 'graph_args --base 1000 -l 0 '
	echo 'graph_category security'
	echo 'graph_vlabel Yum Activity'
	echo 'updates.label Yum Updated'
	echo 'updates.draw AREA'
	echo 'installed.label Yum Installed'
	echo 'installed.draw AREA'
	echo 'erased.label Yum Erased'
	echo 'erased.draw AREA'
	exit 0
fi

echo -n "updates.value "
grep "`date "+%b %d"`" /var/log/yum.log | grep -ci Updated

echo -n "installed.value "
grep "`date "+%b %d"`" /var/log/yum.log | grep -ci Installed

echo -n "erased.value "
grep "`date "+%b %d"`" /var/log/yum.log | grep -ci Erased
