#!/usr/bin/python3

import sys
from pylxd import api

c=api.API()

if len(sys.argv) == 2:
    if sys.argv[1]=="autoconf":
        print("yes")
        sys.exit(0)
    elif sys.argv[1]=="config":
        print("graph_title LXD container disk usage")
        print("graph_args --base 1000 --lower-limit 0")
        print("graph_vlabel Bytes")
        print("graph_category lxd")
        print("graph_info This shows the disk usage of storage in containers. Make sure to install pylxd in python3.")
        for name in c.container_list():
            for disk in c.container_info(name)['disk']:
                print(name+"-"+disk+".label "+name)
                print(name+"-"+disk+".draw LINE2")
        sys.exit(0)

for name in c.container_list():
    for disk in c.container_info(name)['disk']:
        print(name+"-"+disk+".value "+str(c.container_info(name)['disk'][disk]['usage']))
