#!/usr/bin/perl -w
# -*- mode: cperl; mode: autopair -*-
# Magic markers:
#%# family=auto
#%# capabilities=autoconf
# php_fcgi --- Munin plugin for determining the memory usage and
#              number of PHP FastCGI processes.

# Copyright (C) 2010 António P. P. Almeida <appa@perusio.net>

# Author: António P. P. Almeida <appa@perusio.net>

# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# Except as contained in this notice, the name(s) of the above copyright
# holders shall not be used in advertising or otherwise to promote the sale,
# use or other dealings in this Software without prior written authorization.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

=head1 NAME

php_fcgi - Munin plugin to show the Memory anf number of processes used by PHP FastCGI.

=encoding utf8

=head1 APPLICABLE SYSTEMS

Any host running PHP FastCGI.

=head1 MAGIC MARKERS

  #%# family=auto
  #%# capabilities=autoconf

=head1 VERSION

1.0

=head1 BUGS

None known

=head1 AUTHOR

António Almeida <appa@perusio.net>

=head1 REPOSITORY

Source code at http://github.com/perusio/munin-php-cgi

=head1 LICENSE

MIT

=cut

## Support for rounding functions.
use POSIX;

## Munin config method.
if (exists $ARGV[0] and $ARGV[0] eq "config") {

  print "graph_title PHP CGI [MB]\n";
  print "graph_vlabel PHP CGI Memory usage\n";
  print "graph_category php-cgi\n";
  print "graph_args -l 0\n";
  print "php_cgi_ram.label PHP CGI Used RAM\n";
  print "php_cgi_ram.draw LINE2\n";
  print "php_cgi_processes.info Number of PHP CGI processes\n";
  print "php_cgi_processes.label processes\n";

  exit 0;
} else {
  my ($pp, $pm) = eval(`ps u -p \$(pidof php-cgi) | awk 'NR > 1 {pm += \$5} END {print "("NR-1","pm/1024")"}'`);
  printf("php_cgi_ram.value %d\n", ceil($pm));
  print "php_cgi_processes.value $pp\n";
}
