#!/bin/sh
# Plugin to monitor the FreeRadius active users count
# Usage: Link or copy into /etc/munin/node.d/
# Config variables:
#    radwho - radwho binary

radwho=${radwho:-/usr/local/bin/radwho}

if [ "$1" = "config" ]; then
	echo 'graph_title FreeRadius active users count'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel users'
	echo 'graph_noscale true'
	echo 'graph_category other'
	echo 'usercnt.label users'
	echo 'graph_info FreeRadius active users count.'
	echo 'usercnt.info FreeRadius active users count'
	exit 0
fi

echo "usercnt.value $($radwho -rci 2>/dev/null | wc -l)"

