#!/usr/bin/perl

use strict;
use warnings;
use Munin::Plugin::SNMP;
use vars qw($DEBUG);
use Data::Dumper;

$DEBUG = $ENV{'MUNIN_DEBUG'};

my %config = (
        misc64CifsOps	=> 'CifsOps',
        misc64NfsOps 	=> 'NfsOps',
        iscsi64Ops      => 'IscsiOps',
        fcp64Ops        => 'FcpOps',
        misc64HttpOps	=> 'HttpOps',
);

if (defined $ARGV[0] and $ARGV[0] eq 'snmpconf') {
    print "require 1.3.6.1.4.1.789.1.2.2.1.0 [0-9]\n";
    exit 0;
}

my $session = Munin::Plugin::SNMP->session();

if (defined $ARGV[0] and $ARGV[0] eq "config") {

    my ($host, undef, undef, undef) = Munin::Plugin::SNMP->config_session();

    print "host_name $host\n" unless $host eq 'localhost';
    print "graph_title $host OPS \n";
    print "graph_args --base 1000 --lower-limit 0 --rigid\n";
    print "graph_vlabel OPS \n";
    print "graph_category OPS\n";
    print "graph_info This graph shows OPS for the $host NetApp equipment.\n";
    print "graph_order misc64CifsOps misc64NfsOps iscsi64Ops fcp64Ops misc64HttpOps\n";

    foreach my $k (sort keys %config) {
        print "$k.info The number of OPS for $config{$k}.\n";
        print "$k.type COUNTER\n";
        print "$k.label $config{$k}\n";
        print "$k.min 0\n";
	print "$k.draw AREASTACK\n";
    }

    exit 0;
}

my $system = $session->get_hash(
    -baseoid => '1.3.6.1.4.1.789.1.2.2',
    -cols    => {
	27   => 'misc64NfsOps',
	28   => 'misc64CifsOps',
	29   => 'misc64HttpOps',
    },
);

my $block = $session->get_hash(
    -baseoid => '1.3.6.1.4.1.789.1.17',
    -cols    => {
	24   => 'iscsi64Ops',
	25   => 'fcp64Ops',
    },
);

my $tmp->{0} = { %{$system->{0}}, %{$block->{0}}} ;

foreach my $k (keys %config) {
    my $v = 'U';
    $v = $tmp->{0}->{$k} if (defined $tmp);
    print "$k.value $v\n";
}

exit 0;

__END__
