#!/usr/bin/perl

use strict;
use warnings;
use Munin::Plugin::SNMP;
use vars qw($DEBUG);

$DEBUG = $ENV{'MUNIN_DEBUG'};

my %oids = (
        misc64DiskReadBytes => 'DISKUTIL_DISKREADBYTES',
        misc64DiskWriteBytes => 'DISKUTIL_DISKWRITEBYTES',
);

if (defined $ARGV[0] and $ARGV[0] eq 'snmpconf') {
    print "require 1.3.6.1.4.1.789.1.2.2.1.0 [0-9]\n";
    exit 0;
}

my $session = Munin::Plugin::SNMP->session();

if (defined $ARGV[0] and $ARGV[0] eq "config") {

    my ($host, undef, undef, undef) = Munin::Plugin::SNMP->config_session();

    print "host_name $host\n" unless $host eq 'localhost';
    print "graph_title $host  Disk throughput\n";
    print "graph_args --base 1024\n";
    print "graph_vlabel Bytes/\${graph_period} write (-) / read (+)\n";
    print "graph_category disk\n";
    print "graph_info This graph shows DiskUtil calls for the $host NetApp equipment.\n";
    print "graph_order misc64DiskWriteBytes misc64DiskReadBytes\n";

    print "misc64DiskWriteBytes.type COUNTER\n";
    print "misc64DiskWriteBytes.label bps\n";
    print "misc64DiskWriteBytes.min 0\n";
    print "misc64DiskWriteBytes.graph no\n";

    print "misc64DiskReadBytes.type COUNTER\n";
    print "misc64DiskReadBytes.min 0\n";
    print "misc64DiskReadBytes.label bps\n";
    print "misc64DiskReadBytes.negative misc64DiskWriteBytes\n";
    print "misc64DiskReadBytes.info misc64DiskWriteBytes/misc64DiskReadBytes\n";

    exit 0;
}

my $values = $session->get_hash(
    -baseoid => '1.3.6.1.4.1.789.1.2.2',
    -cols    => {
        32  => 'misc64DiskReadBytes',
        33  => 'misc64DiskWriteBytes',
    },
);

foreach my $k (keys %oids) {
    my $v = 'U';
    $v = $values->{0}->{$k} if (defined $values);
    print "$k.value $v\n";
}

exit 0;

__END__
