#!/bin/sh
#
# Plugin to the number of subscribers to a EOC list.
#
# Copyright (C) 2009 - Julien Danjou <julien@danjou.info>
# Licensed under WTFPL
#
# Standard config options you may want to set:
# [eoc_*]
# user list
# env.HOME /var/list
#
# Magic markers - optional - used by installation scripts and
# munin-config:
#
#%# family=manual
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
	echo yes 
	exit 0
fi

LISTNAME=`basename $0 | sed 's/^eoc_subscribers_count_//g' | tr '_' '@'`

if [ "$1" = "config" ]; then

	echo 'graph_title Number of subscribers to '${LISTNAME}
	echo 'graph_vlabel subscribers'
	echo 'graph_category mailinglist'
	echo 'subscribers.label subscribers'
	echo 'subscribers.draw AREA'
        echo 'subscribers.info Number of subscribers to the list'
	exit 0
fi

echo -n subscribers.value\ 
enemies-of-carlotta --name ${LISTNAME} --list | wc -l
