* munin contrib - plugin tests

  Summary:

  Failed 5/1006 subtests

  (less 1 skipped subtest: 1000 okay)

** [0/1] Failing test
*** TODO Failed test 'plugins/snmp/snmp__brocade_ifs: python compile'

    python plugin with error in regular expression string.

#+BEGIN_EXAMPLE
# at t/test.t line 162.
#
# Command: python -m py_compile snmp__brocade_ifs
#
# STDOUT:
#
#
#
# STDERR:
#
# SyntaxError: ('invalid syntax', ('snmp__brocade_ifs', 272, 22, "regex_str = '^snmp_'(.+)'_brocade_ifs'\n"))
#
#
#+END_EXAMPLE


** [0/4] False positives

*** TODO not ok 110 - plugins/system/solaris-memstat: ksh syntax check

  Can't see what's wrong here.  False positive?

#+BEGIN_EXAMPLE
# Failed test 'plugins/system/solaris-memstat: ksh syntax check'
# at t/test.t line 169.
#
# Command: ksh -n solaris-memstat
#
# STDOUT:
#
#
#
# STDERR:
#
# solaris-memstat: syntax error at line 119: `if' unmatched
#
#
#+END_EXAMPLE

*** TODO not ok 191 - plugins/snmp/snmp__webthermometer

  False positive in "checkbashisms". It looks for $HOSTNAME, which is
  set implicitly by bash, but explicitly by the plugin.

#+BEGIN_EXAMPLE
# Subtest: plugins/snmp/snmp__webthermometer
1..2
ok 1 - sh syntax check
not ok 2 - checkbashisms
# Failed test 'checkbashisms'
# at t/test.t line 169.
#
# Command: checkbashisms snmp__webthermometer
#
# STDOUT:
#
#
#
# STDERR:
#
# possible bashism in snmp__webthermometer line 44 ($HOST(TYPE|NAME)):
# HOSTNAME=`echo $HOSTNAME | sed -e 's/\.$//'`
# possible bashism in snmp__webthermometer line 47 ($HOST(TYPE|NAME)):
# echo file $FILE dir $DIR hostname $HOSTNAME linkdir $LINKDIR linkfile $LINKFILE
#
#
# Looks like you failed 1 test of 2.
#+END_EXAMPLE

*** TODO not ok 319 - plugins/rabbitmq/rabbitmq_connections

  False positive in "checkbashisms".

#+BEGIN_EXAMPLE
# Subtest: plugins/rabbitmq/rabbitmq_connections
1..2
ok 1 - sh syntax check
not ok 2 - checkbashisms
# Failed test 'checkbashisms'
# at t/test.t line 169.
#
# Command: checkbashisms rabbitmq_connections
#
# STDOUT:
#
#
#
# STDERR:
#
# possible bashism in rabbitmq_connections line 66 ($"foo" should be eval_gettext "foo"):
# echo "connections.value $(HOME=$HOME rabbitmqctl list_connections | grep -v "^Listing" | grep -v "done.$" | wc -l)"
#
#
# Looks like you failed 1 test of 2.
not ok 319 - plugins/rabbitmq/rabbitmq_connections
# Failed test 'plugins/rabbitmq/rabbitmq_connections'
# at t/test.t line 64.
#+END_EXAMPLE


** [0/1] Blame the CI provider

*** TODO not ok 536 - plugins/network/multi_tcp_ping: perl syntax check

    Perl on travis-ci not built to support threads

#+BEGIN_EXAMPLE
# Failed test 'plugins/network/multi_tcp_ping: perl syntax check'
# at t/test.t line 169.
#
# Command: perl -cw multi_tcp_ping
#
# STDOUT:
#
#
#
# STDERR:
#
# This Perl not built to support threads
# Compilation failed in require at multi_tcp_ping line 75.
# BEGIN failed--compilation aborted at multi_tcp_ping line 75.
#
#
#+END_EXAMPLE
