* munin contrib - plugin tests

  Summary:

  Failed 7/1006 subtests

  (less 1 skipped subtest: 998 okay)


** [0/1] Need to investigate

*** TODO not ok 572 - plugins/network/d-link-dir-655-router-statistics-plugin: ruby syntax check
   
    Need to investigate.

#+BEGIN_EXAMPLE
# Failed test 'plugins/network/d-link-dir-655-router-statistics-plugin: ruby syntax check'
# at t/test.t line 169.
#
# Command: ruby -cw d-link-dir-655-router-statistics-plugin
#
# STDOUT:
#
#
#
# STDERR:
#
# /home/travis/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- auto_gem (LoadError)
# from /home/travis/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
#
#
#+END_EXAMPLE

** [0/4] False positives

*** TODO not ok 110 - plugins/system/solaris-memstat: ksh syntax check

  Can't see what's wrong here.  False positive?

#+BEGIN_EXAMPLE
# Failed test 'plugins/system/solaris-memstat: ksh syntax check'
# at t/test.t line 169.
#
# Command: ksh -n solaris-memstat
#
# STDOUT:
#
#
#
# STDERR:
#
# solaris-memstat: syntax error at line 119: `if' unmatched
#
#
#+END_EXAMPLE

*** TODO not ok 191 - plugins/snmp/snmp__webthermometer

  False positive in "checkbashisms". It looks for $HOSTNAME, which is
  set implicitly by bash, but explicitly by the plugin.

#+BEGIN_EXAMPLE
# Subtest: plugins/snmp/snmp__webthermometer
1..2
ok 1 - sh syntax check
not ok 2 - checkbashisms
# Failed test 'checkbashisms'
# at t/test.t line 169.
#
# Command: checkbashisms snmp__webthermometer
#
# STDOUT:
#
#
#
# STDERR:
#
# possible bashism in snmp__webthermometer line 44 ($HOST(TYPE|NAME)):
# HOSTNAME=`echo $HOSTNAME | sed -e 's/\.$//'`
# possible bashism in snmp__webthermometer line 47 ($HOST(TYPE|NAME)):
# echo file $FILE dir $DIR hostname $HOSTNAME linkdir $LINKDIR linkfile $LINKFILE
#
#
# Looks like you failed 1 test of 2.
#+END_EXAMPLE

*** TODO not ok 319 - plugins/rabbitmq/rabbitmq_connections

  False positive in "checkbashisms".

#+BEGIN_EXAMPLE
# Subtest: plugins/rabbitmq/rabbitmq_connections
1..2
ok 1 - sh syntax check
not ok 2 - checkbashisms
# Failed test 'checkbashisms'
# at t/test.t line 169.
#
# Command: checkbashisms rabbitmq_connections
#
# STDOUT:
#
#
#
# STDERR:
#
# possible bashism in rabbitmq_connections line 66 ($"foo" should be eval_gettext "foo"):
# echo "connections.value $(HOME=$HOME rabbitmqctl list_connections | grep -v "^Listing" | grep -v "done.$" | wc -l)"
#
#
# Looks like you failed 1 test of 2.
not ok 319 - plugins/rabbitmq/rabbitmq_connections
# Failed test 'plugins/rabbitmq/rabbitmq_connections'
# at t/test.t line 64.
#+END_EXAMPLE

*** TODO not ok 538 - plugins/network/ldap_connections

   False positive in checkbashisms at 'ESTABLISHED$"'.

   Still, quite horrible shell code.

#+BEGIN_EXAMPLE
# Subtest: plugins/network/ldap_connections
1..2
ok 1 - sh syntax check
not ok 2 - checkbashisms
# Failed test 'checkbashisms'
# at t/test.t line 169.
#
# Command: checkbashisms ldap_connections
#
# STDOUT:
#
#
#
# STDERR:
#
# possible bashism in ldap_connections line 130 ($"foo" should be eval_gettext "foo"):
# echo "$(echo $ip | sed 's/\./_/g')_${port}.value $(grep "^tcp[46]\{0,1\}\([[:space:]]\{1,\}[[:digit:]]\{1,\}\)\{2\}[[:space:]]\{1,\}$ip[\.:]$port[[:space:]].*ESTABLISHED$" $TEMP_FILE | wc -l | sed 's/[[:space:]]*//g')"
#
#
# Looks like you failed 1 test of 2.
#+END_EXAMPLE


** [0/1] Blame the CI provider

*** TODO not ok 536 - plugins/network/multi_tcp_ping: perl syntax check

    Perl on travis-ci not built to support threads

#+BEGIN_EXAMPLE
# Failed test 'plugins/network/multi_tcp_ping: perl syntax check'
# at t/test.t line 169.
#
# Command: perl -cw multi_tcp_ping
#
# STDOUT:
#
#
#
# STDERR:
#
# This Perl not built to support threads
# Compilation failed in require at multi_tcp_ping line 75.
# BEGIN failed--compilation aborted at multi_tcp_ping line 75.
#
#
#+END_EXAMPLE

