#! /bin/sh
# (c) 2013 - LGPL - Steve Schnepp <steve.schnepp@pwkf.org>

pluginfull="$0"                 # full name of plugin
plugin="${0##*/}"               # name of plugin
pidfile="$MUNIN_PLUGSTATE/munin.$plugin.pid"
cache="$MUNIN_PLUGSTATE/munin.$plugin.value"


if [ ! -r "/sys/class/thermal/thermal_zone0/temp" ]
then
	echo "# Cannot read CPU Temp"
	exit 1
fi


if [ "$1" = "config" ]
then
        cat <<EOF
graph_title CPU Temp
graph_category sensors
graph_vlabel C
thermal_zone0.label Current CPU Temp
EOF
        exit 0
fi

# values
TEMP_MILLI_C=$(cat /sys/class/thermal/thermal_zone0/temp)

if ! type "bc" > /dev/null 2>&1; then echo not found; fi
    echo thermal_zone0.value $(( $TEMP_MILLI_C / 1000 ))
else
    echo thermal_zone0.value $( echo "scale=3; $TEMP_MILLI_C / 1000" | bc )
fi

exit 0
