#!/bin/sh
# -*- sh -*-

: <<=cut

=head1 NAME

multimemory - Munin plugin to monitor memory usage of processes. Which processes
are configured in client-conf.d

=head1 APPLICABLE SYSTEMS

Any system with a compatible ps command.

=head1 CONFIGURATION

There is no default configuration.  This is an example:

  [multimemory]
	 env.os freebsd
     env.names apache2 mysqld php-cgi

Set env.os to freebsd if you are running this script on a machine which doesnt have
GNU sed installed (FreeBSD / OpenBSD / Solaris ...), else set it to linux.

The names are used to grep with directly, after cleaning. So, this plugin
only supports very basic pattern matching. To fix: see multips

=head1 INTERPRETATION

This plugin adds up the RSS of all processes matching the
regex given as the process name, as reported by ps.

=head1 MAGIC MARKERS

  #%# family=manual
  #%# capabilities=autoconf

=head1 VERSION
  0.3 light improvement in FreeBSD part of ps parsing
  0.2 second release, it should now work on machines without GNU sed
  0.1 first release, based on:
    multimemory.in 1590 2008-04-17 18:21:31Z matthias
  As distributed in Debian.

=head1 BUGS

None known

=head1 AUTHOR

Originally: matthias?
Modified by: github.com/dominics github.com/yhager
Thanks to: wix

=head1 LICENSE

GPLv2

=cut

if [ -z "$MUNIN_LIBDIR" ]; then
	MUNIN_LIBDIR="`dirname $(dirname "$0")`"
fi

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ -z "$names" -o -z "$os" ]; then
  echo "Configuration required"
  exit 1
fi

if [ "$1" = "config" ]; then
	echo graph_title Total memory usage
	echo 'graph_category processes'
	echo 'graph_args --base 1024 --vertical-label memory -l 0'
	for name in $names; do
	    	fieldname=$(clean_fieldname $name)
	    	REGEX='\<'"$name"'\>'

		echo "$fieldname.label $name"
		echo "$fieldname.draw LINE2"
		echo "$fieldname.info Processes matching this regular expression: /$REGEX/"
	done
	exit 0
fi

for name in $names; do
        fieldname=$(clean_fieldname $name)
	printf "$fieldname.value "

	if [ "$os" = "freebsd" ]; then
		ps awxo rss,command | grep -w $name | grep -v grep | /usr/bin/awk '{ total += $1 } END { print total * 1024 }'
	else
		ps auxww | grep -w $name | grep -v grep | sed -re 's/[ ]{1,}/ /g' | /usr/bin/cut -d ' ' -f 6 | /usr/bin/awk '{ total = total + $1 } END { print total * 1024 }'
	fi
done
