#!/bin/bash
# -*- sh -*-
: <<=cut

=head1 NAME

sphinx - Munin plugin to display Sphinx status

=head1 CONFIGURATION

Config file must be readable by your munin user.
  [sphinx_*]
  user sphinx

optional is category, default is empty
  [sphinx_*]
  env.category mysql

=head1 AUTHOR

martin fuxa <root@unihost.cz>

=head1 LICENSE

CC

=cut

CATEGORY=${category:-""}

#. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "config" ]; then
  # draw default LINE1
  echo "graph_args --base 1000 -l 0"
  echo "graph_title Sphinx Status"
  echo "graph_category $CATEGORY"
  echo "connections.label   number of connections"
  echo "connections.type    COUNTER"
  echo "command_search.label   number of search command"
  echo "command_search.type    COUNTER"
  echo "queries.label   number of query"
  echo "queries.type    COUNTER"
  echo "query_wall.label   time to process query in seconds"
  echo "query_wall.type    COUNTER"
  exit 0
fi

STAT=`searchd --status`
RT=$?
if [ $RT -eq 0 ]; then
  SEARCHFOR="connections command_search queries query_wall"
  for _sf in $SEARCHFOR; do
    echo -n "$_sf.value "
   #DERIVE or COUNTER only take integer values as an argument # http://munin-monitoring.org/ticket/1193
    echo "$STAT" | grep -E "^$_sf:" | awk -F ": " '{printf "%.0f\n", $2}'
  done
else
  echo "ERROR unexpected result:"
  echo "$STAT"
fi

exit $RT
