#!/bin/bash

if [[ $1 == 'config' ]]; then
	echo "graph_args --base 1000 -l 0"
	echo "graph_title Serveur FTP"
	echo "graph_category Ftp"
	echo "graph_vlabel Stats Proftpd"
	echo "succes.label Login succes"
	echo "succes.draw AREA"
	echo "failed.label Login failed"
	echo "failed.draw AREA"
fi

succes=`cat /var/log/proftpd/proftpd.log | grep -c "successful"`
failed=`cat /var/log/proftpd/proftpd.log | grep -c "Login failed"`

echo "succes.value $succes"
echo "failed.value $failed"
