#!/bin/bash

if [ "$1" == "config" ] ; then
	echo "graph_title HP server fan speed"
	echo "graph_vlabel speed"
	echo "graph_category sensors"
	echo "graph_info This graph shows the speed of the system fans"

	hplog -f | perl -ne 'if ( m/(System|Processor|Virtual)/) { $t=lc($1); $count[$t]++; print $t."_".$count[$t] . ".label " . $t . " fan speed $count[$t] \n"  }'
	exit 0
fi

#ID     TYPE        LOCATION      STATUS  REDUNDANT FAN SPEED 
#1  Var. Speed   Processor Zone  Normal     N/A     Low    ( 10)
#2  Var. Speed   System Board    Normal     N/A     Low    ( 10)
#6  Var. Speed   System Board    Normal     Yes     Low    ( 13)
#ID     TYPE        LOCATION      STATUS  REDUNDANT FAN SPEED 
# 1  Var. Speed   Virtual         Normal     N/A     Low    ( 19)


hplog -f | perl -ne 'if ( m/(System|Processor|Virtual)/) { $t=lc($1); $count[$t]++; m/\( *(\d+)\)/; print "${t}_$count[$t].value $1\n"  }'
