#!/bin/sh
#
# Plugin to count the qmail-remote processes
#
# Magic markers - optional - used by installation scripts and
# munin-config:
#
#%# family=manual
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
        echo "yes"
        exit 0
fi

if [ "$1" = "config" ]; then

	cat <<EOT
graph_title Qmail-remote processes
graph_args --base 1000 -l 0 
graph_vlabel running processes
graph_category Mail
remote.label remote
remote.type GAUGE
EOT
        exit 0
fi

echo -n "remote.value " && pgrep qmail-remote | wc -l
